In [ ]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import gc
import evaluate
from transformers import SegformerForSemanticSegmentation, TrainingArguments, Trainer
from Data_Loader import Sen1Floods11Dataset, training_augmentation
from peft import LoraConfig, get_peft_model

In [ ]:
sen1floods11_data_folder = "../Data/Sen1Floods11/"
splits = sen1floods11_data_folder + "splits/"
SAR_data  = sen1floods11_data_folder + "S1Hand/"
Label_data = sen1floods11_data_folder + "LabelHand/"

In [ ]:
train_files = pd.read_csv(splits + 'flood_train_data.csv',header=None, names=["SAR", "Label"])
val_files = pd.read_csv(splits + 'flood_valid_data.csv',header=None, names=["SAR", "Label"])
test_files = pd.read_csv(splits + 'flood_test_data.csv',header=None, names=["SAR", "Label"])

In [ ]:
train_dataset = Sen1Floods11Dataset(SAR_data, Label_data, train_files, transform=training_augmentation)
val_dataset = Sen1Floods11Dataset(SAR_data, Label_data, val_files)
test_dataset = Sen1Floods11Dataset(SAR_data, Label_data, test_files)

### Custom Loss Functions

In [ ]:
class WeightedLossTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(**inputs)
        logits = outputs.logits
        labels = inputs["labels"]

        upsampled_logits = torch.nn.functional.interpolate(
            logits, size=labels.shape[-2:], mode="bilinear", align_corners=False)
        #Upsampling the segformer output to match the true mask pixel-by-pixel

        class_weights = torch.tensor([1.0, 5.0]).to(self.args.device)
        #The relative weightage to be given to pixels of each class

        loss_fn = nn.CrossEntropyLoss(weight=class_weights, ignore_index=255)
        loss = loss_fn(upsampled_logits, labels)

        return (loss, outputs) if return_outputs else loss

In [ ]:
class SARHybridLossTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        outputs = model(**inputs)
        logits = outputs.logits
        labels = inputs["labels"]

        upsampled_logits = torch.nn.functional.interpolate(
            logits, size=labels.shape[-2:], mode="bilinear", align_corners=False)

        probs = torch.softmax(upsampled_logits, dim=1)
        valid_mask = (labels != 255).float()

        true_land = (labels == 0).float() * valid_mask
        true_water = (labels == 1).float() * valid_mask

        pred_land = probs[:, 0, :, :] * valid_mask
        pred_water = probs[:, 1, :, :] * valid_mask

        # Multi-Class Focal Loss
        gamma = 2.0 #Higher gamma downweights the common(land) class
        eps = 1e-6

        focal_land = -true_land * ((1.0 - pred_land) ** gamma) * torch.log(pred_land + eps)
        focal_water = -true_water * ((1.0 - pred_water) ** gamma) * torch.log(pred_water + eps)
        focal_loss = (focal_land + focal_water).sum() / (valid_mask.sum() + eps)

        #Dice Loss
        intersection = torch.sum(pred_water * true_water, dim=(-2, -1))
        denominator = torch.sum(pred_water, dim=(-2, -1)) + torch.sum(true_water, dim=(-2, -1))

        dice_coeff = (2.0 * intersection + eps) / (denominator + eps)
        dice_loss = 1.0 - torch.mean(dice_coeff)


        total_loss = (0.5 * focal_loss) + (0.5 * dice_loss)

        return (total_loss, outputs) if return_outputs else total_loss

### Training Setup

In [ ]:
metric = evaluate.load("mean_iou")

def compute_metrics(eval_pred):
    with torch.no_grad():
        logits, labels = eval_pred

        #Converting the model output logits to the class predictions
        logits_tensor = torch.from_numpy(logits)
        upsampled_logits = torch.nn.functional.interpolate(
            logits_tensor, size=labels.shape[-2:], mode="bilinear", align_corners=False)
        predictions = upsampled_logits.argmax(dim=1).numpy()

        metrics = metric.compute(
            predictions=predictions,
            references=labels,
            num_labels=2,
            ignore_index=255,
            reduce_labels=False)

        per_category_iou = metrics["per_category_iou"]
        return {
            "mIoU": metrics["mean_iou"],
            "pixel_accuracy": metrics["mean_accuracy"],
            "land_iou": per_category_iou[0],
            "flood_water_iou": per_category_iou[1]}

In [ ]:
model_id = "nvidia/segformer-b2-finetuned-ade-512-512"

id2label = {0: "land", 1: "flood_water"}
label2id = {"land": 0, "flood_water": 1}

### Model Runs

In [ ]:
#Using normal cross entropy loss function

model_base = SegformerForSemanticSegmentation.from_pretrained(
    model_id,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True)


training_args = TrainingArguments(
    output_dir="./segformer_results",
    learning_rate=2e-5,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none")


trainer = Trainer(
    model=model_base,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics)


trainer.train()

model_base.save_pretrained("../Models/Cross_entropy")

del model_base
del trainer
gc.collect()
torch.cuda.empty_cache()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/6.88k [00:00<?, ?B/s]

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `150`.

pytorch_model.bin: reconstructing file:   0%|          |  0.00B /  110MB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/380 [00:00<?, ?it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b2-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 768, 1, 1]) vs model:torch.Size([2, 768, 1, 1])
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

model.safetensors: reconstructing file:   0%|          |  0.00B /  110MB

model.safetensors: downloading bytes:           |  0.00B

/usr/local/lib/python3.13/dist-packages/datasets/features/image.py:406: UserWarning: Downcasting array dtype int64 to int32 to be compatible with 'Pillow'
  warnings.warn(f"Downcasting array dtype {dtype} to {dest_dtype} to be compatible with 'Pillow'")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#Using weighted cross entropy loss function

model_base = SegformerForSemanticSegmentation.from_pretrained(
    model_id,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True)

training_args = TrainingArguments(
    output_dir="./segformer_results",
    learning_rate=2e-5,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none")


trainer = WeightedLossTrainer(
    model=model_base,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics)


trainer.train()

model_base.save_pretrained("../Models/Weighted_Cross_entropy")

del model_base
del trainer
gc.collect()
torch.cuda.empty_cache()

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `150`.

Loading weights:   0%|          | 0/380 [00:00<?, ?it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b2-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 768, 1, 1]) vs model:torch.Size([2, 768, 1, 1])
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

/usr/local/lib/python3.13/dist-packages/datasets/features/image.py:406: UserWarning: Downcasting array dtype int64 to int32 to be compatible with 'Pillow'
  warnings.warn(f"Downcasting array dtype {dtype} to {dest_dtype} to be compatible with 'Pillow'")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#Using FOCAL+DICE loss function

model_base = SegformerForSemanticSegmentation.from_pretrained(
    model_id,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True)

training_args = TrainingArguments(
    output_dir="./segformer_results",
    learning_rate=2e-5,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none")


trainer = SARHybridLossTrainer(
    model=model_base,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics)


trainer.train()

model_base.save_pretrained("../Models/Focal_Dice")

del model_base
del trainer
gc.collect()
torch.cuda.empty_cache()

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `150`.

Loading weights:   0%|          | 0/380 [00:00<?, ?it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b2-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 768, 1, 1]) vs model:torch.Size([2, 768, 1, 1])
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

/usr/local/lib/python3.13/dist-packages/datasets/features/image.py:406: UserWarning: Downcasting array dtype int64 to int32 to be compatible with 'Pillow'
  warnings.warn(f"Downcasting array dtype {dtype} to {dest_dtype} to be compatible with 'Pillow'")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
# FOCAL+DICE + DoRA

model_base = SegformerForSemanticSegmentation.from_pretrained(
    model_id,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True)

dora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules="all-linear",
    lora_dropout=0.1,
    bias="none",
    use_dora=True,
    modules_to_save=["decode_head"]
)

model_dora = get_peft_model(model_base, dora_config)

training_args = TrainingArguments(
    output_dir="./segformer_results",
    learning_rate=5e-5,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none")


trainer = SARHybridLossTrainer(
    model=model_dora,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics)


trainer.train()

model_dora.save_pretrained("../Models/DoRA_16")

del model_base
del model_dora
del trainer
gc.collect()
torch.cuda.empty_cache()

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `150`.

Loading weights:   0%|          | 0/380 [00:00<?, ?it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b2-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 768, 1, 1]) vs model:torch.Size([2, 768, 1, 1])
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

/usr/local/lib/python3.13/dist-packages/datasets/features/image.py:406: UserWarning: Downcasting array dtype int64 to int32 to be compatible with 'Pillow'
  warnings.warn(f"Downcasting array dtype {dtype} to {dest_dtype} to be compatible with 'Pillow'")

In [ ]:
# FOCAL+DICE + DoRA (Rank 32)

model_base = SegformerForSemanticSegmentation.from_pretrained(
    model_id,
    num_labels=2,
    id2label=id2label,
    label2id=label2id,
    ignore_mismatched_sizes=True)

dora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules="all-linear",
    lora_dropout=0.1,
    bias="none",
    use_dora=True,
    modules_to_save=["decode_head"]
)

model_dora = get_peft_model(model_base, dora_config)

training_args = TrainingArguments(
    output_dir="./segformer_results",
    learning_rate=5e-5,
    num_train_epochs=5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    eval_strategy="epoch",
    save_strategy="no",
    logging_steps=20,
    fp16=True,
    dataloader_num_workers=2,
    report_to="none")


trainer = SARHybridLossTrainer(
    model=model_dora,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics)


trainer.train()

model_dora.save_pretrained("../Models/DoRA_32")

del model_base
del model_dora
del trainer
gc.collect()
torch.cuda.empty_cache()

[transformers] You passed `num_labels=2` which is incompatible to the `id2label` map of length `150`.

Loading weights:   0%|          | 0/380 [00:00<?, ?it/s]

[transformers] SegformerForSemanticSegmentation LOAD REPORT from: nvidia/segformer-b2-finetuned-ade-512-512
Key                           | Status   |
------------------------------+----------+-----------------------------------------------------------------------------------------------------
decode_head.classifier.weight | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150, 768, 1, 1]) vs model:torch.Size([2, 768, 1, 1])
decode_head.classifier.bias   | MISMATCH | Reinit due to size mismatch - ckpt: torch.Size([150]) vs model:torch.Size([2])

Notes:
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

/usr/local/lib/python3.13/dist-packages/datasets/features/image.py:406: UserWarning: Downcasting array dtype int64 to int32 to be compatible with 'Pillow'
  warnings.warn(f"Downcasting array dtype {dtype} to {dest_dtype} to be compatible with 'Pillow'")